<!DOCTYPE html>
<html>
<head>
<title>Registration</title>
</head>
<body>
	<h3>Welcome  ${first_name}  ${last_name}  ${email_address}  to All Cures Info.</h3>
	<p>${linkverfiy}
	<p>Please confirm your registration by following the next step.</p>	
	<p>Click on the link given below or copy and paste the entire link to browser address bar.</p>
	<p>This confirmatory step is necessary for registration of your username and password into our system.</p>
	<p>For any clarification or specific information,  please contact support@etheriumtech.com</p>
	<p>Thank you.</p>
	<p>All Cures Info Team</p>
</body>
</html>
